### ISSUE TITLE
No component found named : sunrise

### ISSUE THREAD

**Issue by xiace** [ORRTIZ/bbasic#1]
controller.xml： 

```
<view-map name="main" type="screen" page="component://sunrise/widget/sunrise-Screens.xml#main"/>
```

but there is not such folder like sunrise

**Comment by PierreSmits** [comment]
Thanks for reporting. This has been solved with commit https://github.com/ORRTIZ/bbasic/commit/a640b1b6b8e54759bbdf336048ec558342b4b70a
